index:
    path: /
    defaults: { _controller: 'App\Controller\MailController::index' }

mail_welcome:
    path: /mail/welcome
    defaults: {_controller: 'App\Controller\MailController::sendWelcomeMail' }
