index:
    path: /mail
    defaults: { _controller: 'App\Controller\MailController::index' }

mail_welcome:
    path: /mail/welcome/{email}/{password}
    defaults: {_controller: 'App\Controller\MailController::sendWelcomeMail' }

checkEmail:
    path: /mail/see
    defaults: {_controller: 'App\Controller\MailController::checkEmailFront' }
